# Generated by Django 6.0.6 on 2026-06-16 10:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(unique=True)),
                ('total_eggs_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transaction_count', models.IntegerField(default=0)),
                ('average_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily Revenue',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='Flock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flock_id', models.CharField(max_length=50, unique=True)),
                ('breed', models.CharField(max_length=100)),
                ('initial_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('culled', 'Culled')], default='active', max_length=20)),
                ('date_started', models.DateField()),
                ('date_ended', models.DateField(blank=True, null=True)),
                ('housing_type', models.CharField(default='H-type cages', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('eggs_collected', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('broken_eggs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('defective_eggs', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('good_eggs', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('collection_time', models.TimeField(blank=True, null=True)),
                ('eggs_per_hen', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hen_day_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('hen_housed_production', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='egg_productions', to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='EggProduction.flock')),
            ],
            options={
                'verbose_name_plural': 'Egg Production',
                'ordering': ['-record_date'],
                'unique_together': {('flock', 'record_date')},
            },
        ),
        migrations.CreateModel(
            name='EggGrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('average_weight', models.FloatField(help_text='grams', validators=[django.core.validators.MinValueValidator(0)])),
                ('egg_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading', to='EggProduction.eggproduction')),
            ],
            options={
                'verbose_name_plural': 'Egg Grading',
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_type', models.CharField(choices=[('egg_production', 'Egg Production'), ('sales_volume', 'Sales Volume'), ('sales_price', 'Sales Price'), ('hen_performance', 'Hen Performance')], max_length=30)),
                ('model_type', models.CharField(choices=[('arima', 'ARIMA'), ('mlr', 'Multiple Linear Regression'), ('hybrid', 'Hybrid Model')], max_length=20)),
                ('forecast_date', models.DateField()),
                ('forecasted_value', models.FloatField()),
                ('upper_bound', models.FloatField(blank=True, null=True)),
                ('lower_bound', models.FloatField(blank=True, null=True)),
                ('mean_absolute_percentage_error', models.FloatField(blank=True, help_text='MAPE %', null=True)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('model_parameters', models.JSONField(blank=True, default=dict, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='EggProduction.flock')),
            ],
            options={
                'verbose_name_plural': 'Forecasts',
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='HenPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('average_weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('feed_consumption', models.FloatField(help_text='kg', validators=[django.core.validators.MinValueValidator(0)])),
                ('water_consumption', models.FloatField(help_text='liters', validators=[django.core.validators.MinValueValidator(0)])),
                ('mortality_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('injured', 'Injured'), ('culled', 'Culled')], max_length=20)),
                ('temperature', models.FloatField(blank=True, help_text='°C', null=True)),
                ('humidity', models.FloatField(blank=True, help_text='%', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='EggProduction.flock')),
            ],
            options={
                'verbose_name_plural': 'Hen Performance',
                'ordering': ['-record_date'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.FloatField()),
                ('predicted_value', models.FloatField()),
                ('error', models.FloatField()),
                ('percentage_error', models.FloatField()),
                ('absolute_error', models.FloatField()),
                ('evaluation_date', models.DateField()),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='EggProduction.forecast')),
            ],
            options={
                'verbose_name_plural': 'Model Performance',
                'ordering': ['-evaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('eggs_sold', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('buyer_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='EggProduction.flock')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sales Records',
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('data_entry', 'Data Entry'), ('forecast_run', 'Forecast Run'), ('model_train', 'Model Training'), ('data_export', 'Data Export'), ('system_error', 'System Error')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(default='info', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'System Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('manager', 'Manager')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Roles',
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('egg_production', 'Egg Production'), ('sales_volume', 'Sales Volume'), ('sales_price', 'Sales Price'), ('hen_performance', 'Hen Performance')], max_length=30)),
                ('record_date', models.DateField()),
                ('value', models.FloatField()),
                ('rolling_avg_7', models.FloatField(blank=True, null=True)),
                ('rolling_avg_30', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_series', to='EggProduction.flock')),
            ],
            options={
                'ordering': ['-record_date'],
                'indexes': [models.Index(fields=['flock', 'data_type', 'record_date'], name='EggProducti_flock_i_565bd7_idx')],
            },
        ),
    ]
