# Generated by Django 6.0.6 on 2026-06-28 15:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EggProduction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('age_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_aa', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_a', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_b', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_small', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_broken', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_decode', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_source', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='HarvestForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('grade', models.CharField(choices=[('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('predicted_qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('arima', 'ARIMA'), ('mlr', 'Multiple Linear Regression'), ('hybrid', 'Hybrid Model'), ('lstm', 'LSTM Neural Network')], max_length=20)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('r2_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('rmse', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aic_score', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('arima_order', models.CharField(blank=True, help_text='Format: (p,d,q)', max_length=20, null=True)),
                ('pkl_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('training_rows', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Model Versions',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('age_weeks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('age_days', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hen_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dead_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('culled_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('feed_bags', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('eggs_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('pct_hen_day', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pct_hen_housed', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('fcr', models.DecimalField(blank=True, decimal_places=3, help_text='Feed Conversion Ratio', max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('grade', models.CharField(choices=[('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('predicted_trays', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=2)),
                ('quantity_trays', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_tray', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Sales Items',
            },
        ),
        migrations.CreateModel(
            name='SalesTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sale_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff'), ('manager', 'Manager')], default='staff', max_length=20)),
                ('assigned_house', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.DeleteModel(
            name='DailyRevenue',
        ),
        migrations.RemoveField(
            model_name='egggrading',
            name='egg_production',
        ),
        migrations.AlterUniqueTogether(
            name='eggproduction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='eggproduction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='eggproduction',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='modelperformance',
            name='forecast',
        ),
        migrations.RemoveField(
            model_name='henperformance',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='henperformance',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='flock',
        ),
        migrations.RemoveField(
            model_name='salesrecord',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='systemlog',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='timeseriesdata',
            name='EggProducti_flock_i_565bd7_idx',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='flock',
            options={'ordering': ['-date_started']},
        ),
        migrations.RenameField(
            model_name='flock',
            old_name='breed',
            new_name='breed_strain',
        ),
        migrations.RenameField(
            model_name='flock',
            old_name='initial_count',
            new_name='initial_hen_count',
        ),
        migrations.AddField(
            model_name='flock',
            name='house_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='flock',
            unique_together={('house_no', 'date_started')},
        ),
        migrations.AddField(
            model_name='gradinglog',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_logs', to='EggProduction.flock'),
        ),
        migrations.AddField(
            model_name='harvestforecast',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_forecasts', to='EggProduction.flock'),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvestforecast',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_forecasts', to='EggProduction.modelversion'),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionlog',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_logs', to='EggProduction.flock'),
        ),
        migrations.AddField(
            model_name='salesforecast',
            name='model_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecasts', to='EggProduction.modelversion'),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='flock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='EggProduction.flock'),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='EggProduction.salestransaction'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='EggGrading',
        ),
        migrations.DeleteModel(
            name='EggProduction',
        ),
        migrations.DeleteModel(
            name='Forecast',
        ),
        migrations.DeleteModel(
            name='ModelPerformance',
        ),
        migrations.DeleteModel(
            name='HenPerformance',
        ),
        migrations.DeleteModel(
            name='SalesRecord',
        ),
        migrations.DeleteModel(
            name='SystemLog',
        ),
        migrations.RemoveField(
            model_name='timeseriesdata',
            name='flock',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.RemoveField(
            model_name='flock',
            name='current_count',
        ),
        migrations.RemoveField(
            model_name='flock',
            name='date_ended',
        ),
        migrations.RemoveField(
            model_name='flock',
            name='flock_id',
        ),
        migrations.RemoveField(
            model_name='flock',
            name='housing_type',
        ),
        migrations.AlterUniqueTogether(
            name='gradinglog',
            unique_together={('flock', 'log_date')},
        ),
        migrations.AlterUniqueTogether(
            name='harvestforecast',
            unique_together={('flock', 'model_version', 'forecast_date', 'grade')},
        ),
        migrations.AlterUniqueTogether(
            name='productionlog',
            unique_together={('flock', 'log_date')},
        ),
        migrations.AlterUniqueTogether(
            name='salesforecast',
            unique_together={('model_version', 'forecast_date', 'grade')},
        ),
        migrations.DeleteModel(
            name='TimeSeriesData',
        ),
    ]
