# Generated by Django 6.0.6 on 2026-07-10 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EggProduction', '0002_gradinglog_harvestforecast_modelversion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradinglog',
            options={'ordering': ['-grading_date']},
        ),
        migrations.AlterModelOptions(
            name='productionlog',
            options={'ordering': ['-production_date']},
        ),
        migrations.RenameField(
            model_name='gradinglog',
            old_name='eggs_a',
            new_name='cracked_eggs',
        ),
        migrations.RenameField(
            model_name='gradinglog',
            old_name='eggs_aa',
            new_name='grade_extra_large',
        ),
        migrations.RenameField(
            model_name='gradinglog',
            old_name='eggs_b',
            new_name='grade_jumbo',
        ),
        migrations.RenameField(
            model_name='gradinglog',
            old_name='eggs_broken',
            new_name='grade_large',
        ),
        migrations.RenameField(
            model_name='gradinglog',
            old_name='eggs_decode',
            new_name='grade_medium',
        ),
        migrations.RenameField(
            model_name='gradinglog',
            old_name='eggs_small',
            new_name='grade_peewee',
        ),
        migrations.RenameField(
            model_name='gradinglog',
            old_name='log_date',
            new_name='grading_date',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='culled_count',
            new_name='daily_culls',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='dead_count',
            new_name='daily_mortality',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='eggs_total',
            new_name='eggs_collected',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='feed_bags',
            new_name='feed_consumed_bags',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='fcr',
            new_name='feed_conversion_ratio',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='pct_hen_day',
            new_name='hen_day_production',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='pct_hen_housed',
            new_name='hen_housed_production',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='hen_count',
            new_name='live_hen_count',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='remarks',
            new_name='management_remarks',
        ),
        migrations.RenameField(
            model_name='productionlog',
            old_name='log_date',
            new_name='production_date',
        ),
        migrations.AlterUniqueTogether(
            name='gradinglog',
            unique_together={('flock', 'grading_date')},
        ),
        migrations.AddField(
            model_name='gradinglog',
            name='grade_pullets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gradinglog',
            name='grade_small',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='gradinglog',
            name='source',
            field=models.CharField(default='hardware', max_length=20),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='mae',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='productionlog',
            unique_together={('flock', 'production_date')},
        ),
        migrations.RemoveField(
            model_name='gradinglog',
            name='eggs_source',
        ),
        migrations.RemoveField(
            model_name='gradinglog',
            name='eggs_total',
        ),
    ]
