# Generated by Django 6.0.6 on 2026-07-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EggProduction', '0004_align_sales_dataset_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harvestforecast',
            name='grade',
            field=models.CharField(choices=[('jumbo', 'Jumbo'), ('xl', 'XL'), ('large', 'Large'), ('medium', 'Medium'), ('small', 'Small'), ('pullets', 'Pullets'), ('pewee', 'Pewee'), ('broken', 'Broken'), ('cull', 'Cull'), ('sack', 'Sack')], max_length=20, verbose_name='egg size'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='grade',
            field=models.CharField(choices=[('jumbo', 'Jumbo'), ('xl', 'XL'), ('large', 'Large'), ('medium', 'Medium'), ('small', 'Small'), ('pullets', 'Pullets'), ('pewee', 'Pewee'), ('broken', 'Broken'), ('cull', 'Cull'), ('sack', 'Sack')], max_length=20, verbose_name='egg size'),
        ),
    ]
