# Generated by Django 6.0.6 on 2026-07-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EggProduction', '0005_alter_harvestforecast_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesforecast',
            name='predicted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='harvestforecast',
            name='grade',
            field=models.CharField(choices=[('overall', 'Overall'), ('jumbo', 'Jumbo'), ('xl', 'XL'), ('large', 'Large'), ('medium', 'Medium'), ('small', 'Small'), ('pullets', 'Pullets'), ('pewee', 'Pewee'), ('broken', 'Broken'), ('cull', 'Cull'), ('sack', 'Sack')], max_length=20, verbose_name='egg size'),
        ),
        migrations.AlterField(
            model_name='salesforecast',
            name='grade',
            field=models.CharField(choices=[('overall', 'Overall'), ('jumbo', 'Jumbo'), ('xl', 'XL'), ('large', 'Large'), ('medium', 'Medium'), ('small', 'Small'), ('pullets', 'Pullets'), ('pewee', 'Pewee'), ('broken', 'Broken'), ('cull', 'Cull'), ('sack', 'Sack')], max_length=20, verbose_name='egg size'),
        ),
    ]
