# Generated by Django 6.0.6 on 2026-07-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EggProduction', '0006_salesforecast_predicted_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionlog',
            name='fcr',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Feed Conversion Ratio', max_digits=8, null=True),
        ),
    ]
