# Generated by Django 6.0.6 on 2026-08-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EggProduction', '0008_forecast_validation_and_intervals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
