# Generated by Django 6.0.6 on 2026-09-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EggProduction', '0010_modelversion_comparison_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelversion',
            name='arima_order',
            field=models.CharField(blank=True, help_text='Format: (p,d,q)', max_length=80, null=True),
        ),
    ]
