# Generated by Django 6.0.6 on 2026-09-27 04:07

import django.db.models.deletion
from django.db import migrations, models


def clear_sales_flock_links(apps, schema_editor):
    SalesTransaction = apps.get_model('EggProduction', 'SalesTransaction')
    SalesTransaction.objects.update(flock=None)


class Migration(migrations.Migration):

    dependencies = [
        ('EggProduction', '0011_alter_modelversion_arima_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='flock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_transactions', to='EggProduction.flock'),
        ),
        migrations.RunPython(clear_sales_flock_links, migrations.RunPython.noop),
    ]
